//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elavid.SpeedyScrabble {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elavid.SpeedyScrabble.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you,1222421
        ///I,1052546
        ///to,823661
        ///the,770161
        ///a,563578
        ///and,480214
        ///that,413389
        ///it,388320
        ///of,332038
        ///me,312326
        ///what,285826
        ///is,282222
        ///in,266544
        ///this,249860
        ///know,241548
        ///for,216535
        ///no,212463
        ///have,210523
        ///my,210429
        ///just,196810
        ///not,195058
        ///do,194183
        ///be,191823
        ///on,191646
        ///your,188060
        ///was,184170
        ///we,181863
        ///with,169586
        ///so,169088
        ///but,159109
        ///all,158281
        ///well,155201
        ///are,152650
        ///he,150009
        ///oh,148780
        ///about,142750
        ///right,137218
        ///get,126849
        ///here,124368
        ///out,121867
        ///going,121435
        ///like,121194
        ///yeah,121 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string common_words {
            get {
                return ResourceManager.GetString("common_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAHED
        ///AAHING
        ///AAHS
        ///AALII
        ///AALIIS
        ///AALS
        ///AARDVARK
        ///AARDVARKS
        ///AARDWOLF
        ///AARDWOLVES
        ///AARGH
        ///AARRGH
        ///AARRGHH
        ///AASVOGEL
        ///AASVOGELS
        ///ABACA
        ///ABACAS
        ///ABACI
        ///ABACK
        ///ABACTERIAL
        ///ABACUS
        ///ABACUSES
        ///ABAFT
        ///ABAKA
        ///ABAKAS
        ///ABALONE
        ///ABALONES
        ///ABAMP
        ///ABAMPERE
        ///ABAMPERES
        ///ABAMPS
        ///ABANDON
        ///ABANDONED
        ///ABANDONER
        ///ABANDONERS
        ///ABANDONING
        ///ABANDONMENT
        ///ABANDONMENTS
        ///ABANDONS
        ///ABAPICAL
        ///ABAS
        ///ABASE
        ///ABASED
        ///ABASEDLY
        ///ABASEMENT
        ///ABASEMENTS
        ///ABASER
        ///ABASERS
        ///ABASES
        ///ABASH
        ///ABASHED
        ///ABASHES
        ///ABASHING
        ///ABASHMENT
        ///ABASHMENTS
        ///ABASIA
        ///ABASIAS
        ///ABASING
        ///ABATABLE
        ///ABATE
        ///ABATED
        ///ABATEMENT
        ///ABATEME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string twl98 {
            get {
                return ResourceManager.GetString("twl98", resourceCulture);
            }
        }
    }
}
